name: R CI

on:
  push:
    branches: [main, refactor-main-account-docs]
  pull_request:
    branches: [main, refactor-main-account-docs]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      R_LIBS_USER: ${{ github.workspace }}/.Rlibrary
      RENV_PATHS_LIBRARY: ${{ github.workspace }}/.Rlibrary
      TZ: UTC
      _R_CHECK_SYSTEM_CLOCK_: FALSE
      NOT_CRAN: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Create R library directory
        run: mkdir -p ${{ env.R_LIBS_USER }}

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: r-${{ runner.os }}-${{ hashFiles('DESCRIPTION') }}
          restore-keys: r-${{ runner.os }}-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libgit2-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfreetype6-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev \
            libfontconfig1-dev \
            libglpk-dev \
            libx11-dev \
            libxt-dev \
            libudunits2-dev \
            libgdal-dev \
            libgeos-dev \
            libproj-dev \
            libcairo2-dev

      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          use-lockfile: false
          extra-packages: |
            devtools
            remotes
            pkgdown
            
      - name: Install local package
        run: devtools::install(upgrade = "never")
        shell: Rscript {0}

      - name: Lint code
        run: lintr::lint_package()
        shell: Rscript {0}

      - name: Run tests
        run: devtools::test()
        shell: Rscript {0}

      - name: Check code (CRAN-style)
        run: devtools::check()
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov(token = Sys.getenv("CODECOV_TOKEN"))
        shell: Rscript {0}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  api-tests:
    runs-on: ubuntu-latest
    needs: build  # ✅ Waits for build to complete

    env:
      R_LIBS_USER: ${{ github.workspace }}/.Rlibrary
      RENV_PATHS_LIBRARY: ${{ github.workspace }}/.Rlibrary
      TZ: UTC
      NOT_CRAN: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Restore cached R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: r-${{ runner.os }}-${{ hashFiles('DESCRIPTION') }}
          restore-keys: r-${{ runner.os }}-

      - name: Install endpoint test dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          use-lockfile: false
          extra-packages: |
            devtools
            testthat
            jsonlite
            jose
            callr
            withr
            here
            httr
            plumber

      - name: Run API endpoint tests
        run: testthat::test_file("api/tests/test_endpoints.R")
        shell: Rscript {0}
