name: R CI

on:
  push:
    branches: [main, refactor-main-account-docs]
  pull_request:
    branches: [main, refactor-main-account-docs]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      R_LIBS_USER: ${{ github.workspace }}/.Rlibrary
      TZ: UTC
      _R_CHECK_SYSTEM_CLOCK_: FALSE
      NOT_CRAN: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libgit2-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfreetype6-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev \
            libfontconfig1-dev \
            libglpk-dev \
            libx11-dev \
            libxt-dev \
            libudunits2-dev \
            libgdal-dev \
            libgeos-dev \
            libproj-dev \
            libcairo2-dev

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: ${{ runner.os }}-r-

      - name: Install package dependencies
        run: |
          install.packages(
            c("devtools", "remotes", "testthat", "covr", "lintr", "tidyverse", "pkgdown", "R6","uuid"),
            repos = "https://cloud.r-project.org"
          )
          devtools::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Lint code
        run: lintr::lint_package()
        shell: Rscript {0}

      - name: Run tests
        run: devtools::test()
        shell: Rscript {0}

      - name: Check code (CRAN-style)
        run: devtools::check()
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}

      # Optional: pkgdown site (if using)
      # - name: Build pkgdown site
      #   run: pkgdown::build_site()
      #   shell: Rscript {0}
